POST http://localhost:5000/api/notes
content-type: application/json

{
    "title": "This is a third note",
    "text": "This is fun xxxx"
}

###

GET http://localhost:5000/api/notes/63bf180aa107eba8cce89e46
content-type: application/json

{}

###

GET http://localhost:5000/api/notes
content-type: application/json

{}

###

PATCH http://localhost:5000/api/notes/63c048e668b0bc91a8bad5f2
content-type: application/json

{
    "title": "My second note",
    "text": "This is fun again"
}

###

DELETE http://localhost:5000/api/notes/63bf180aa107eba8cce89e46
content-type: application/json

{}

###

POST http://localhost:5000/api/users/signup
content-type: application/json

{
    "username": "Florian",
    "email": "florian@test.com",
    "password": "12345"
}

###

POST http://localhost:5000/api/users/login
content-type: application/json

{
    "username": "Florian",
    "email": "florian@test.com",
    "password": "12345"
}

###

GET http://localhost:5000/api/users/
content-type: application/json

{
    "username": "Florian",
    "password": "12345"
}

###

POST http://localhost:5000/api/users/logout
content-type: application/json

{
}